pool:
  vmImage: 'ubuntu-latest'
trigger:
  - master
steps:
- task: CopyFiles@2
  displayName: 'Copy files to: $(build.artifactstagingdirectory)/Temapltes'
  inputs:
    SourceFolder: deployment
    Contents: '*.json'
    TargetFolder: '$(build.artifactstagingdirectory)/Temapltes'
- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install --production'
- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'